version: "2"
services:
    orientdb:
      image: orientdb:latest
      ports:
        - "2424:2424"
        - "2480:2480"
      environment:
        ORIENTDB_ROOT_PASSWORD: 'testorient'
      volumes:
        - ./config:/opt/orientdb/config
        - ./databases:/opt/orientdb/databases
        - ./backup:/opt/orientdb/backup
